import { Owner } from './owner.js';
import { Barista } from './barista.js';
import { CoffeShop } from './coffeshop.js';
import { Visitor } from './visitor.js';

const co = new CoffeShop('Kave', 'Lviv', 'Menu', 5);
console.log(co);
co.addMenuItem('kav');
co.addMenuItem('kav2');
co.addMenuItem('kav3');
// co.removeMenuItem('kav3');
co.hireBarista('Petro');
co.hireBarista('Petro2');
co.hireBarista('Petro3');
co.fireBarista('Petro');
console.log(co);
co.takeOrder('kav');
co.serveCustomer();
console.log(co);
co.calculateMonthlyProfit();
